name: CI

on:
  push:
    branches: ["*"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - uses: pnpm/action-setup@master
      - name: Run install Git's default auto-crlf line endings
        run: |
          pnpm install --frozen-lockfile || true
      - name: Run install with CRLF line endings
        run: |
          $content = Get-Content pnpm-lock.yaml -Raw
          Set-Content pnpm-lock.yaml -Value $content -NoNewline -Encoding UTF8
          pnpm install --frozen-lockfile || true
      - name: Run install with LF line endings
        run: |
          $content = Get-Content pnpm-lock.yaml -Raw
          $content = $content -replace "`r`n", "`n"
          Set-Content pnpm-lock.yaml -Value $content -NoNewline -Encoding UTF8
          pnpm install --frozen-lockfile || true
