name: CI

on:
  push:
    branches: ["*"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - uses: pnpm/action-setup@master
      - name: Install dependencies
        run: pnpm --version && pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
